apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: saas-starter
  labels:
    app: graphql
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5000
      protocol: TCP
      name: graphql
  selector:
    app: graphql